name: Quality Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pycodestyle mypy pydocstyle
    - name: Analysing the code with pylint, pycodestyle, mypy and pydocstyle
      run: |
        readarray -t files < <(git ls-files '*.py'|grep -Ev '__init__.py')
        pylint "${files[@]}"
        pycodestyle "${files[@]}"
        mypy --strict "${files[@]}"
        pydocstyle "${files[@]}"
